# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://timtaubert.de
title: Tim Taubert
subtitle:
author: Tim Taubert
description:

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"
time_format: ""
timezone: "Europe/Berlin"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml

exclude: ['deploy.sh', 'pngcrush.sh', 'docker']

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root_url: /
permalink: /blog/:year/:month/:title/
category_dir: blog/categories
markdown: rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart
highlighter: pygments # default python pygments have been replaced by pygments.rb

plugins:
  - jekyll-sitemap

collections:
  talks:
    output: true
    permalink: /talks/:path/

recent_posts: 6       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: "<!--more-->"

titlecase: true       # Converts page and post titles to titlecase
